export const SING_UP_STARTED = 'SING_UP_STARTED'
export const SING_UP_COMPLETED = 'SING_UP_COMPLETED'
export const SING_UP_FAILED = 'SING_UP_FAILED'

export const SING_IN_STARTED = 'SING_IN_STARTED'
export const SING_IN_COMPLETED = 'SING_IN_COMPLETED'
export const SING_IN_FAILED = 'SING_IN_FAILED'
export const USER_LOGOUT = 'USER_LOGOUT'